### ISSUE TITLE
NixOS Question

### ISSUE THREAD

**Issue by bananabr34d** [Moskas/qtile-config#1]
I really like your NixOS-config and how you've set up qtile, but I can't figure out how you declaratively add qtile to your NixOS config if it is in a separate repo.  Do you simply install your NixOS flake and then git clone the qtile config or is there some other mechanism for pulling down the qtile repo within Nix that I'm not aware?

**Comment by Moskas** [comment]
At the moment I'm manually git cloning it after install. I've tried fetching it using a home-manager and it worked really well. The caveat was that way it was read only and I needed to  update commit info for each change.
You can source the config with home-manager like so:
```nix
  home.file = {
    ".config/qtile".source = pkgs.fetchFromGitea {
      domain = "codeberg.org";
      owner = "Moskas";
      repo = "qtile-org";
      rev = "d643434dd9";
      sha256 = "sha256-9wEoLw3/ma1mvt2Jj2xPc6LejP2HIpBzqxQ+h7E50t8=";
    };
  };
 ```
 Or you can move the directory to the flake and make it source the qtile config dir on each rebuild using the xdg.configFile option in home-manager.
```nix
xdg.confileFile.qtile.source = ./qtile;
```
I'm doing it manually because I'm just constantly tweaking it so the ease of edits is more important to me and I didn't want to "pollute" my flake with separate python files to keep it 100% nix.
